cmake_minimum_required(VERSION 3.0.2)
project(epgeneral_wheeltec_integration)
find_package(catkin REQUIRED COMPONENTS rospy std_msgs std_srvs)
catkin_python_setup()
catkin_package()
catkin_install_python(PROGRAMS scripts/finalize_map.py scripts/native_navigation.py scripts/prepare_native_map.py scripts/check_ready.py DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
install(DIRECTORY launch config DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})
